version: '2'
services:
  server:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      DATABASE_URL: $DATABASE_URL
      PORT: ${PORT}