version: '2'
services:
  server:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: $DATABASE_URL
      PORT: ${PORT}
      EXTERNAL_API_CHIVO_URL: ${EXTERNAL_API_CHIVO_URL}
      EXTERNAL_API_QR_GENERATOR_URL: ${EXTERNAL_API_QR_GENERATOR_URL}
      EXTERNAL_API_BTC_BEACH_URL: ${EXTERNAL_API_BTC_BEACH_URL}
      EXTERNAL_API_QR_GENERATOR_URL: ${EXTERNAL_API_QR_GENERATOR_URL}
      EXTERNAL_API_QR_GENERATOR_ACCESS_TOKEN: ${EXTERNAL_API_QR_GENERATOR_ACCESS_TOKEN}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_BIG_QUERY_DATASET: ${GOOGLE_BIG_QUERY_DATASET}
      GOOGLE_BIG_QUERY_TABLE_INVOICE_EVENTS: ${GOOGLE_BIG_QUERY_TABLE_INVOICE_EVENTS}
      GOOGLE_PUBSUB_TOPIC_PUBSUB_TO_BIG_QUERY: ${GOOGLE_PUBSUB_TOPIC_PUBSUB_TO_BIG_QUERY}